#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#$ -o /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Equipo2/scripts/out_logs/DownloadData.out
#$ -e /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Equipo2/scripts/out_logs/DownloadData.err
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N DownloadData
#
# Memory
#$ -l vf=7G
#
# Send an email after the job has finished
#$ -m e
#$ -M sc0bly16@hotmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
# Write your commands in the next line
cd /mnt/atgc-d1/bioinfoII/rnaseq/BioProject_2025/Equipo2/data

wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/057/SRR31738157/SRR31738157_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/063/SRR31738163/SRR31738163_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/061/SRR31738161/SRR31738161_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/060/SRR31738160/SRR31738160_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/059/SRR31738159/SRR31738159_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/058/SRR31738158/SRR31738158_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/057/SRR31738157/SRR31738157_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/055/SRR31738155/SRR31738155_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/061/SRR31738161/SRR31738161_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/063/SRR31738163/SRR31738163_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/062/SRR31738162/SRR31738162_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/059/SRR31738159/SRR31738159_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/056/SRR31738156/SRR31738156_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/056/SRR31738156/SRR31738156_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/055/SRR31738155/SRR31738155_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/058/SRR31738158/SRR31738158_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/062/SRR31738162/SRR31738162_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR317/060/SRR31738160/SRR31738160_2.fastq.gz
